### PR TITLE
add i logs

### PR DESCRIPTION
**Pull request by tarek360**

### CODE REVIEW

**Comment by tarek360** [comment]
## Koshry Report

|Status|Files are protected and can't be modified, ask @tarek360 to modify|
|:-:|-|
|❌|[File --> **.circleci/config.yml**](https://github.com/tarek360/koshry/pull/1/files#diff-1d37e48f9ceff6d8030570cd36286a61)|

**Comment by corombo** [comment]
## Koshry Report

|Status|Files are protected and can't be modified, ask @tarek360 to modify|
|:-:|-|
|❌|[File --> **.circleci/config.yml**](https://github.com/tarek360/koshry/pull/1/files#diff-1d37e48f9ceff6d8030570cd36286a61)|

**Comment by corombo** [comment]
## Koshry Report

|Status|Files are protected and can't be modified, ask @tarek360 to modify|
|:-:|-|
|❌|[File --> **.circleci/config.yml**](https://github.com/tarek360/koshry/pull/1/files#diff-1d37e48f9ceff6d8030570cd36286a61)|

**Comment by corombo** [comment]
LGTM

**Comment by corombo** [comment]
zz

**Pull request merged**
