### PR TITLE
fix file url for enterprise

### PR DESCRIPTION
**Pull request by tarek360**
**fix file url for github enterprise..**

### CODE REVIEW

**Comment by corombo** [comment]
## Koshry Report

|Status|JaCoCo Coverage Report|Coverage|
|:-:|-|:-:|
|🔥|[io/github/tarek360/koshry/url/GithubFileUrlGenerator](https://github.com/tarek360/koshry/pull/18/files#diff-e9db1dec666f1c4eb6dc086174fd84ce)|0%|
|✅|**Project Total Coverage**|**88%**|

**Comment by corombo** [comment]
## Koshry Report

|Status|JaCoCo Coverage Report|Coverage|
|:-:|-|:-:|
|✅|[io/github/tarek360/rules/coverage/CsvParserImpl$parse$new Function1() {$$$}](https://github.com/tarek360/koshry/pull/18/files#diff-0c226e87d6586e52f8611d127e04557f)|100%|
|✅|[io/github/tarek360/rules/coverage/JacocoCoverageRule](https://github.com/tarek360/koshry/pull/18/files#diff-50a1ae3c9c4d8b7726afcebf58a7a3c2)|82%|
|✅|[io/github/tarek360/rules/coverage/CsvParserImpl](https://github.com/tarek360/koshry/pull/18/files#diff-0c226e87d6586e52f8611d127e04557f)|100%|
|✅|[io/github/tarek360/rules/coverage/JacocoCoverageRule$JacocoCoverageRuleBuilder](https://github.com/tarek360/koshry/pull/18/files#diff-50a1ae3c9c4d8b7726afcebf58a7a3c2)|100%|
|✅|[io/github/tarek360/rules/coverage/ClassCoverage](https://github.com/tarek360/koshry/pull/18/files#diff-03aae68f99f0d9cf20b3cf75c19ce6dd)|100%|
|🔥|[io/github/tarek360/koshry/url/GithubFileUrlGenerator](https://github.com/tarek360/koshry/pull/18/files#diff-4820ad8eb61d3660f734984ffac22aba)|0%|
|✅|**Project Total Coverage**|**88%**|

**Comment by corombo** [comment]
## Koshry Report

|Status|JaCoCo Coverage Report|Coverage|
|:-:|-|:-:|
|✅|[io/github/tarek360/rules/coverage/CsvParserImpl$parse$new Function1() {$$$}](https://github.com/tarek360/koshry/pull/18/files#diff-0c226e87d6586e52f8611d127e04557f)|100%|
|✅|[io/github/tarek360/rules/coverage/JacocoCoverageRule](https://github.com/tarek360/koshry/pull/18/files#diff-50a1ae3c9c4d8b7726afcebf58a7a3c2)|82%|
|✅|[io/github/tarek360/rules/coverage/CsvParserImpl](https://github.com/tarek360/koshry/pull/18/files#diff-0c226e87d6586e52f8611d127e04557f)|100%|
|✅|[io/github/tarek360/rules/coverage/JacocoCoverageRule$JacocoCoverageRuleBuilder](https://github.com/tarek360/koshry/pull/18/files#diff-50a1ae3c9c4d8b7726afcebf58a7a3c2)|100%|
|✅|[io/github/tarek360/rules/coverage/ClassCoverage](https://github.com/tarek360/koshry/pull/18/files#diff-03aae68f99f0d9cf20b3cf75c19ce6dd)|100%|
|✅|[io/github/tarek360/koshry/url/GithubFileUrlGenerator](https://github.com/tarek360/koshry/pull/18/files#diff-4820ad8eb61d3660f734984ffac22aba)|100%|
|✅|[io/github/tarek360/koshry/utility/Md5Generator](https://github.com/tarek360/koshry/pull/18/files#diff-226a2e3f2cd63b3227b33dc4498675d7)|100%|
|✅|**Project Total Coverage**|**89%**|

**Comment by tarek360** [comment]
## Koshry Report

|Status|No more JPG files, Use WebP.||
|:-:|-|:-:|
|❌|File: /app/src/main/res/drawable/photo.jpg||

**Review by Meshl-555 — COMMENTED** [review]
None .

**Pull request merged**
